### ISSUE TITLE
About Curve Formula for Uniawap V3

### ISSUE THREAD

**Issue by PeppaCat** [atiselsts/uniswap-v3-liquidity-math#4]
Hi Atis. Thanks for the great paper. I got confused about the derivation of the Eq(2.2) in the original Uniswap V3 paper. I wonder can we get it from the first principle (maybe from Figure 2 in that paper)?

**Comment by atiselsts** [comment]
It's a good question. Some images would be good, like you say Fig. 2 in the whitepaper is relevant.

Here's how I think about it. The goal is to move the liquidity curve so that at the point `a` the amount of y reserves is zero, and so that at the point `b` the x reserves is zero. The only thing that matters for this is the y coordinate of `a` and the x coordinate of `b`. We need to find these coordinates.

The locations of the points `a` and `b` are fully determined by two known things:
1) The slope of the line `y=P*x` on which the point sits, that it, the price P of y in terms of x 
2) How far the point is on that line from the center of the coordinate system - that is, the virtual liquidity L of the position.

Make a system of two equations:
```
y=P*x
L^2=xy
```

Replace y with P*x and solve for x:
```
L^2=P*x^2
L=sqrt(P)*x
x=L/sqrt(P)
```

Same way, solve for y and `y=L*sqrt(P)`.

The x coordinate of the point `b` is `L/sqrt(P_b)`, and the y coordinate of the point a is `L*sqrt(P_a)`. These values are the amounts the liquidity curve needs to be shifted, so if we plug them in the equation 2.1 we get the equation 2.2.

**Comment by PeppaCat** [comment]
Thank you, Atis, for the detailed explanation! It is extremely clear to me now.
